spring:
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: smtp@mailtrap.io
    password: 2638d88aefa8641d0e568925667a9308
    protocol: smtp # Thêm protocol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: live.smtp.mailtrap.io # Thêm để đảm bảo kết nối
  datasource:
    url: jdbc:postgresql://dpg-d0c7i6adbo4c73ddc7g0-a:5432/clothes_jtfi
    driverClassName: org.postgresql.Driver
    username: tungnt26
    password: mjccXnuQd7gDaYQLBVnDRDHW1patWaH5
  jpa:
    hibernate:
      ddl-auto: update
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
    show-actuator: true
vnpay:
  tmnCode: YOUR_TMN_CODE
  hashSecret: YOUR_HASH_SECRET
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay/return
server:
  base-url: https://backend-xutc.onrender.com
logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG