spring:
  datasource:
    url: jdbc:postgresql://dpg-d0c7i6adbo4c73ddc7g0-a.render-database.com:5432/clothes_jtfi
    driverClassName: org.postgresql.Driver
    username: tungnt26
    password: mjccXnuQd7gDaYQLBVnDRDHW1patWaH5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    server:
      servlet:
        encoding:
          force: true
          charset: UTF-8
          enabled: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
    show-actuator: true
